Fix for #16: Add a 404 page
tessel/tessel.io pull request #113
Opened 2017-05-23 09:26 UTC by marzepani

Added 404 route and changed email to team@tessel.io
([Issue #16](https://github.com/tessel/tessel.io/issues/16))

2017-05-23 18:29 UTC, Frijol commented
Hm, I'm still getting 
![screen shot 2017-05-23 at 11 28 52 am](https://cloud.githubusercontent.com/assets/454690/26369938/14b98196-3fab-11e7-8816-bbe4d2d90767.png)

when I run locally

2017-05-23 18:30 UTC, Frijol requested changes

2017-05-23 18:30 UTC, Frijol commented on views/error.jade
> +          a(href='mailto:team@tessel.io') team@tessel.io
Good catch!

2017-05-24 09:54 UTC, marzepani commented
Had to move the router below the static files check. Please re-test. Thx
![screen shot 2017-05-24 at 11 51 28](https://cloud.githubusercontent.com/assets/3640237/26397762/aedea6b2-4077-11e7-9ca9-421c68fbb0af.png)

2017-05-30 13:12 UTC, marzepani commented
@Frijol do you still get no error page?

2017-05-31 16:53 UTC, Frijol commented
Looks good, thanks!

2017-05-31 16:53 UTC, Frijol approved these changes

2017-05-31 16:53 UTC, merged